---
development:
  dialect: postgres
  database: wryteup_dev
  user: postgres
  password: postgres
  host: appdb
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/wryteup.co_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/wryteup.co_production?sslmode=disable"}}
