version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: appdb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wryteup_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      default:
        aliases:
          - database
  migrate:
    image: migrate/migrate
    container_name: app_migrator
    networks:
      - default
    volumes:
      - .:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@database:5432/wryteup_dev?sslmode=disable", "up", "3"]
    depends_on:
      - db
    links:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
      - migrate
    container_name: wryteup_dev
    networks:
      - default
    ports:
      - '9001:9001'
    volumes:
      - .:/go/src/app

volumes:
  pgdata:

networks:
  default: