version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: appdb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wryteup_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    container_name: wryteup_dev
    networks:
      - default
    ports:
      - '9001:9001'
    volumes:
      - .:/go/src/app

volumes:
  pgdata:

networks:
  default: