CREATE TABLE IF NOT EXISTS write_up_tags (
  id UUID UNIQUE PRIMARY KEY,
  write_up_id UUID NOT NULL REFERENCES write_ups(id) ON DELETE CASCADE,
  tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create index using BTREE
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_write_up_and_tag"
ON write_up_tags USING btree (write_up_id, tag_id);