CREATE TABLE IF NOT EXISTS write_up_tags (
  id UUID UNIQUE PRIMARY KEY,
  write_up_id UUID NOT NULL REFERENCES write_ups(id) ON DELETE CASCADE,
  tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX write_up_tags_write_up_id_idx ON public.write_up_tags (write_up_id,tag_id);
